### PR TITLE
#13277: Modify the cloned Mistral7B to become Qwen2-7B implementation.

### PR DESCRIPTION
**Pull request by cthsieh**
### Ticket

#13277

### Problem description
Port model Qwen2-7B to run on the TT Wormhole device.

### What's changed
Create a directory in `models/demos/wormhole/qwen2_7b`.

### Checklist

According to #13277, there are 5 modifications on mistral needed to make it become qwen2.

* [x] Model configuration (tensor dimensions)
* [x] Bias of Q, K, and V projections
* [x] RoPE (Rotary Position Embeddings)
* [x] Tokenizer
* [x] Weight format

### CODE REVIEW

**Comment by cthsieh** [comment]
### Status of c43b8f9c260e317189a5ac4acce2ef507e9e0c7d

When running the Qwen2-7B model on the TT device, the model inference does not yield satisfactory results. While the model produces coherent output (not random characters), the quality of the responses is suboptimal and far from ideal. 

#### Example

```
prompt: write a short poem about London in English
output:

London is a beautiful city with many famous places to visit. Here are the
London is a city
London is a beautiful city. It is the capital of England. it is the capital of the United United United the United the United capital of the United the
London is a capital of the United the United the
London is a city beautiful city. it is the of the the capital of the United the the
London is a city of the the
London is a the capital of the the city city city
London is a the city capital of
```

Obviously, the model behaves like a dummy poet.

#### Analysis

The issue appears to stem from the model's lack of **robustness** when faced with even minor precision loss. Precision loss is commonly introduced during deployment on devices to optimize memory and bandwidth by using shorter data types, such as float8. While this approach works well for many models, it significantly impacts the performance of Qwen2-7B.

We observed that by simply converting many tensors from `ttnn.bfloat8_b` (the default type used by Mistral) to `ttnn.bfloat16`, the PCC can increase significantly from 60% to 80%, indicating that precision loss is a contributing factor to the degraded performance.

#### Root Cause

The issue is particularly evident around the softmax operation. (Don't be nervous. 😸 The softmax implementation itself is correct. It's the inherent semantics of softmax make the problem unavoidable.)

The attention scores fed into softmax for the Qwen2-7B model are extremely large (in the range of hundreds),

```
(Pdb) p ttnn.to_torch(attn)[0,:,0,0]
TorchTensor([  213.0000,   159.0000,   108.5000, -1208.0000,    94.0000,
               169.0000,   171.0000,    40.2500,    34.0000,    33.0000,
              1216.0000,    33.0000,    21.8750,    36.2500,   141.0000,
              2384.0000,    70.5000,   221.0000,   175.0000,   103.5000,
               170.0000,    37.0000,    37.7500,    60.7500,    56.7500,
                25.1250,    57.7500,    26.7500], dtype=torch.bfloat16)
```

whereas for other models like Mistral, the scores are much smaller (around zero).

```
(Pdb) p ttnn.to_torch(attn)[0,:,0,0]
TorchTensor([-0.5000, -0.6172, -0.1973, -0.6680, -0.2656, -0.7891, -0.9844,
              0.3125, -0.4160, -0.3750, -0.3848, -0.4688, -0.3711, -0.6211,
             -0.7656, -0.8906, -0.2275,  0.0505,  0.1816, -0.0332, -0.1069,
             -0.0325, -0.2402, -0.2031, -0.1904, -0.8008, -0.4297, -0.3984,
             -0.4082,  0.4023, -0.1865,  0.0444], dtype=torch.bfloat16)
```

Since softmax is a **non-linear** operation, even small variations in large numbers lead to significant deviations in the output. This issue does not occur to the same extent with smaller numbers, as seen with the Mistral model. The code below demonstrates this statement.

```python
import torch
print(torch.softmax(torch.tensor([100., 101., 102.]), dim=0))
# tensor([0.0900, 0.2447, 0.6652])
print(torch.softmax(torch.tensor([0.100, 0.101, 0.102]), dim=0))
# tensor([0.3330, 0.3333, 0.3337])
```

Let’s further investigate where those large attention scores come from. Compared to Mistral, Qwen2 introduces additional **bias** tensors for the Q, K, and V projections (while Mistral doesn't have). It's the bias tensors containing large numbers. As the code below shows, the K bias tensor contains values up to -160 and 166.

```
import torch
from transformers import AutoTokenizer, Qwen2ForCausalLM

target = 'Qwen/Qwen2-7B'
model = Qwen2ForCausalLM.from_pretrained(target)
k_bias = model.state_dict()["model.layers.0.self_attn.k_proj.bias"]
print(torch.mean(torch.abs(k_bias))) # tensor(8.1455)
print(torch.min(k_bias)) # tensor(-160.)
print(torch.max(k_bias)) # tensor(166.)
```

#### Proposed Solution

To verify this hypothesis, we can address the precision issue by eliminating any precision loss compared to the native PyTorch computations. The potential sources of precision loss include:

1. **Data Type Assignment**: Reviewing and adjusting the data types assigned to each tensor, ensuring they are consistent with PyTorch’s original settings.
2. **Numerical Algorithms**: Ensuring that the numerical algorithms used in `ttnn` align with those in PyTorch to prevent any discrepancies that could introduce further precision loss.

By addressing these two areas, we should be able to improve the performance of the Qwen2-7B model on the TT device.

**Comment by cthsieh** [comment]
I tried using `ttnn.bfloat16` on ALL tensors of Qwen2-7B, but got the following out-of-memory error.

```
E       RuntimeError: TT_THROW @ /home/cthsieh/tt-metal/tt_metal/impl/allocator/allocator.cpp:143: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 135790592 B DRAM buffer across 12 banks, where each bank needs to store 11317248 B
```

**Comment by uaydonat** [comment]
Which device are you using? N150 or N300? N150 only has 12GB of dram. To use bfloat16 for all weights, you need at least 14GB.

Our experience is that bfloat8_b is usually enough. You can maybe convert just the softmax inputs and outputs to bfloat16?

Also, for all matmuls, make sure you are using math_fidelity=ttnn.MathFidelity.HiFi2 which is necessary to get bfloat8b accuracy.

**Comment by cthsieh** [comment]
## Status of cc6dd42c60d8b6251f63b68b16280d52f0d7064d

* Progress: By fixing RoPE, the model has shown promising results in generating reasonable and contextually appropriate responses.
* Challenges: Still unable to fully meet the PCC requirements.

### Example

By initializing `dtype = ttnn.torch8_b` to `TtTransformer`:
```
prompt: write a short poem about London in English
output:

Sure, here's a short poem about London:

London, oh London,
A city full of life and sound,
With its tall buildings and busy streets,
And its people, always on the move

The hustle and bustle of the city
Is what makes Londoner loves
The sights and sounds of the city
Are that can never be lost

From the Tower Bridge to the Thames
And the parks and the museums
London is a city of diversity
And a place of endless fun
So if you're ever in London
Take in all it has to offer
And you'll see see why it's a city
That's always in love
```

On the other hand, by applying `ttnn.torch16` to the model:
```
prompt: write a short poem about London in English
output:

London is a city of grandeur and might,
With towering buildings and streets that are bright,
The Thames runs through the heart of the city,
And the people here are always on the go.

The streets are filled with people from all walks of life,
From the rich and famous to the common man,
The city is a melting pot of cultures and languages,
And the food of the world is served here.

The Tower of London stands tall and proud,
A symbol of the city's rich and storied past,
The British Museum holds treasures from all over the world,
And the Royal Family's grandeur is a sight.

The parks of London are a sight to behold,
From the bustling streets of So to the quiet lanes of So
The city is a placeuring place of contrasts,
And a place of wonder and of the unknown.
```

Both the responses look pretty and much better than before. This should prove that the model structure and weight loading are correct.

### Recent Changes: RoPE Implementation Updated

* The RoPE referred here is **not** the advanced dynamic RoPE we originally proposed in the design document, because careful code tracing of the Qwen2 model in the Transformer library revealed that the [typical RoPE](https://github.com/huggingface/transformers/blob/ad1a250719a508524d1b0d089f7a3c5c0e9b6725/src/transformers/modeling_rope_utils.py#L29) is still applied when short sequences are provided.
* The RoPE implementation cloned from the [given Mistral example](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/wormhole/mistral7b) **cannot** be directly applied to Qwen2 due to differences in data layout assumptions between the two models, though the algorithmic idea is the same.
* Read below if you are really interested in the details.

#### Rotating a Vector in 2D

In the context of RoPE, rotation helps encode positional information in the model's input embeddings.

To rotate a 2D vector, you use the following formula derived from trigonometry. Given a 2D vector `(x, y)`, and a rotation angle `theta`, the rotated vector `(x', y')` is calculated as:

```
x' = x * cos(theta) - y * sin(theta)
y' = x * sin(theta) + y * cos(theta)
```

#### RoPE on a Larger Vector (e.g., 128 dimensions)

Token embeddings can be much larger than just two dimensions (128 in Qwen2). The idea is to apply the rotation operation in **2D subspaces** within the larger-dimensional embedding space.

1. **Embedding Vector Structure**:
   Let’s assume you have a token embedding vector of length 128, such that:

   ```
   [v1, v2, v3, ..., v128]
   ```

2. **Divide into Pairs**:
   RoPE is applied to each specific pair of dimensions in the embedding. So, you treat the vector as 64 pairs of 2D vectors:
   ```
   [v1, v65], [v2, v66], ..., [v64, v128]
   ```

Each pair `[v(i), v(i+64)]` is a 2D vector that can be rotated using the same kind of trigonometric operation described earlier.

Note that different models may assume different data arrangements. The formula provided above applies specifically to [our version of Qwen2-7B](https://github.com/huggingface/transformers/blob/e782e95e3465b66a377c0a7fe95f8f10cd87459d/src/transformers/models/qwen2/modeling_qwen2.py#L182). The Mistral example, however, follows a different approach:

   ```
   [v1, v2], [v3, v4], ..., [v127, v128]
   ```

Interestingly, even models with the same name but from different sources can have varying data arrangement assumptions. In our investigation, the [Mistral model](https://github.com/huggingface/transformers/blob/e782e95e3465b66a377c0a7fe95f8f10cd87459d/src/transformers/models/mistral/modeling_mistral.py#L119) in the Hugging Face Transformer library uses a different assumption compared to [the version of Mistral in your example](https://github.com/tenstorrent/tt-metal/blob/757e59be60c596a6f65756bd29e2ab28483d542b/models/demos/wormhole/mistral7b/tt/mistral_common.py#L74). Careful attention is required when porting models to avoid compatibility issues.

### PCC

PCC values are computed by tests.

```
$ python3 models/demos/wormhole/qwen2_7b/scripts/get_qwen2_weights.py --weights_path <path/to/qwen2/weights>
$ export QWEN2_CKPT_DIR=<path/to/qwen2/weights>
$ export QWEN2_TOKENIZER_PATH=<path/to/qwen2/weights>
$ export QWEN2_CACHE_PATH=<path/to/qwen2/weight_cache>
$ python3 -m pytest models/demos/wormhole/qwen2_7b/tests/test_qwen2_model.py
```

The result for `dtype = ttnn.bfloat8_b` is as follows.

| Token | PCC | Type |
|-------|------|------|
| 0 | 0.9846506775387012 | prefill |
| 1 | 0.8799932753123203 | prefill |
| 2 | 0.9878372520955442 | prefill |
| 3 | 0.9849852922234221 | prefill |
| 4 | 0.9038908947493449 | decode |
| 5 | 0.3710412102448615 | decode |
| 6 | 0.6036486472624594 | decode |
| 7 | 0.39462940832954296 | decode |

The PCC initially appears strong but declines rapidly after the decoding phase. This suggests that the reference model and the TT codes produce diverse responses. However, as demonstrated in the earlier example, what the TT codes produce is still quite reasonable. This presents an interesting phenomenon.

### Next Step

* Adjust dtype and the compute kernel setting to fit the PCC requirements. (Can it be possible?)

**Comment by cthsieh** [comment]
> Which device are you using? N150 or N300? N150 only has 12GB of dram. To use bfloat16 for all weights, you need at least 14GB.
> 

N150. So All bfloat16 is impossible.

> Our experience is that bfloat8_b is usually enough. You can maybe convert just the softmax inputs and outputs to bfloat16?
> 

We observed that bfloat8_b can still produce a "reasonable" response though the response is different from that of the reference model (all bfloat16) given the same prompt. 🤔 

> Also, for all matmuls, make sure you are using math_fidelity=ttnn.MathFidelity.HiFi2 which is necessary to get bfloat8b accuracy.

Will study that. Thanks suggestion.

**Comment by uaydonat** [comment]
> We observed that bfloat8_b can still produce a "reasonable" response though the response is different from that of the reference model (all bfloat16) given the same prompt. 🤔

Yes, very small changes in math and precision affects the tokens. It can only get the same tokens as reference if you run all layers exactly the same.

That's why, when we bring up models we do not aim to match the reference tokens exactly. The implementation can still be correct even if the tokens are not exact match, especially if the output makes sense. We also use pcc, perplexity, or benchmark scores to assess the accuracy.

**Comment by cthsieh** [comment]
> ... The implementation can still be correct even if the tokens are not exact match, ... 
> We also use pcc ... to assess the accuracy.

Thanks @uaydonat for the comments.

My question is that the two statements above seem contradictory. You mentioned that you're also using PCC (Pearson Correlation Coefficient) to assess accuracy, but in my understanding, a high PCC score typically indicates that the same tokens are being produced (with same condition of sampling) as in the reference model. So, with PCC, we are still comparing the generated tokens.

In my case, the TT implementation has a low PCC but still produces a coherent response. Do you think this is acceptable? 

As you mentioned also metric perplexity, I’m planning to use it to evaluate the quality of the model's output. If the perplexity score is good, would it be reasonable to conclude that the model implementation is acceptable, even if the PCC score is low?

**Comment by uaydonat** [comment]
> > ... The implementation can still be correct even if the tokens are not exact match, ...
> > We also use pcc ... to assess the accuracy.
> 
> Thanks @uaydonat for the comments.
> 
> My question is that the two statements above seem contradictory. You mentioned that you're also using PCC (Pearson Correlation Coefficient) to assess accuracy, but in my understanding, a high PCC score typically indicates that the same tokens are being produced (with same condition of sampling) as in the reference model. So, with PCC, we are still comparing the generated tokens.
> 
> In my case, the TT implementation has a low PCC but still produces a coherent response. Do you think this is acceptable?
> 
> As you mentioned also metric perplexity, I’m planning to use it to evaluate the quality of the model's output. If the perplexity score is good, would it be reasonable to conclude that the model implementation is acceptable, even if the PCC score is low?

We use PCC to compare a single (or few) token(s) against the reference, not the whole output text since as soon as a different token is generated the rest of the tokens will be different.

PCC is just an approximation, it gives us a clue about the correctness but it is not always a good indication whether the model is correct or not.

Yes, if the model is generating coherent responses, this is a good sign. However, the best way to see if the model is correct is to compare perplexity, and even better if the benchmark scores are close the reference scores.

**Pull request merged**
